### ISSUE TITLE
Current HTML output looks horrible (on Windows)

### ISSUE THREAD

**Issue by JacquesCarette** [plfa/plfa.github.io#591] opened 2021-09-01 18:34 UTC
As of Sep. 1, this is what I get if I head over to [https://plfa.github.io/Naturals/](https://plfa.github.io/Naturals/):
![image](https://user-images.githubusercontent.com/1855141/131724475-be3932be-7134-477c-b8e2-8f27b2a4ff16.png)

as rendered by Firefox 91.0.2 on Windows. I get pretty much the same thing with Chrome on Windows.

On the other hand, it looks quite reasonable on Chrome on my MacBook.

**Comment by wenkokke** [comment] 2021-09-01 19:26
Whoa, that's... *very* special... gotta say, I kinda like it? But on the other hand, I'd like PLFA to be a usable resource, not an art project. I'm guessing this has to do with the custom we're using, @Altariarite?

**Comment by wenkokke** [comment] 2021-09-01 19:26
Duplicate of #582.

**Comment by Altariarite** [comment] 2021-09-01 23:25
>  I'm guessing this has to do with the custom we're using, @Altariarite?

Whoa, that looks funky. I think the custom font is at fault here, though I am not sure why... For example, all characters in "zero" should be coming from the same font (which is mononoki), so I am not sure at the moment why they end up in different sizes.

**Comment by Altariarite** [comment] 2021-09-01 23:27
Hi Wen,
I am on vacation without a Windows computer at hand. I will be back in
Edinburgh on 6th Sep. Do you think it is best that we roll back the change
for the moment?

Sorry for the trouble caused!

Best,
Yuanting

**Comment by wadler** [comment] 2021-09-02 12:00
Thanks for raising this issue. I hope we can track and fix, but Wen is the expert here.

**Comment by Beal8** [comment] 2021-09-02 19:44
On my local copy I removed everywhere the 'DejaVu mononoki Symbola Droid' font from the style.css file and everything is okay now if it can help

**Comment by fangyi-zhou** [comment] 2021-09-04 10:18
https://fangyi.io/plfa.github.io/Fonts/
https://fangyi.io/plfa.github.io/Naturals/

Could you check whether this page renders correctly on your end?

**Comment by fangyi-zhou** [comment] 2021-09-04 10:21
Disclaimer: I'm not a font magician, but I tried to merge Dejavu, mononoki and Symbola (without Droid), and it is somewhat fine on Windows (tested on my own machine). However, some additional tweaking is required since some symbols are no longer in the correct width, e.g. ℓ, ⦂, ⨆, 〔.

**Comment by JacquesCarette** [comment] 2021-09-04 10:55
The Naturals page looks great. The Fonts page looks 'as expected' from the comments.

**Comment by Altariarite** [comment] 2021-09-07 10:32
> Disclaimer: I'm not a font magician, but I tried to merge Dejavu, mononoki and Symbola (without Droid), and it is somewhat fine on Windows (tested on my own machine). However, some additional tweaking is required since some symbols are no longer in the correct width, e.g. ℓ, ⦂, ⨆, 〔.

@fangyi-zhou The reason these symbols are no longer in the correct width is: the fonts (Dejavu, mononoki, Symbola) are all in different widths.

ℓ and ⦂ are from mononoki, ⨆ is from Symbola, and Droid was included for 〔, which is a CJK symbol (in this case where you doesn't include Droid, I believe the operating system is picking a fallback font to display the symbol). 

The original buggy font was merged using FontForge on MacOS, and symbols that should be monospaced were set to have the same width. For reasons unknown to me, the result is buggy on Windows. 

It would be great if you could share the software you are using or change the width of these symbols in your result. Thanks!

**Comment by fangyi-zhou** [comment] 2021-09-07 10:57
I used FontForge on windows, and I didn't change the width of fonts because I was doing a quick hack. I'll investigate a bit more when I have time.

**Comment by wenkokke** [comment] 2021-09-20 14:42
Can someone confirm this is fixed? @JacquesCarette?

**Comment by fangyi-zhou** [comment] 2021-09-20 14:44
I didn’t submit a patch for the font. I hosted my own instance for a quick preview. 

Fangyi

— sent from a mobile device, apologies for typos

**Comment by Beal8** [comment] 2021-09-20 14:56
I just checked on a windows machine and everything was fine.

**Comment by JacquesCarette** [comment] 2021-09-20 14:57
When I now got to the page in the original problem (and like pages), they look good for me.

**Comment by wenkokke** [comment] 2021-09-23 19:40
> I didn’t submit a patch for the font. I hosted my own instance for a quick preview.

Yes, I used a different fix for the font provided by @leahneukirchen. Thanks, Leah!

**Comment by leahneukirchen** [comment] 2021-09-23 21:11
Oh, good that worked out. :D

**Comment by fangyi-zhou** [comment] 2021-09-24 09:30
> > I didn’t submit a patch for the font. I hosted my own instance for a quick preview.
> 
> Yes, I used a different fix for the font provided by @leahneukirchen. Thanks, Leah!

Ah, sorry I didn't see a fix being pushed to `web` branch. I'll cherry-pick that commit to the Chinese version later.

**Closed as completed** 2021-10-08 14:23 UTC
